version: '3.1'

services:
  redis:
    image: redis
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
  redis-commander:
    image: rediscommander/redis-commander
    container_name: 'redis-commander'
    restart: always
    ports:
      - '8082:8082'
    environment:
      REDIS_HOSTS: local:redis:6379
      PORT: '8082'
    links: 
      - redis
    depends_on: 
      - redis

  mongodb:
    image: mongo
    container_name: 'mongodb'
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    container_name: 'mongo-express-container'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links: 
      - mongodb
    depends_on:
      - mongodb
